# Generated by Django 5.1 on 2024-08-24 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("deadline", models.DateTimeField()),
                ("yes_votes", models.BigIntegerField()),
                ("no_votes", models.BigIntegerField()),
                ("executed", models.BooleanField(default=False)),
                ("blockchain_txn_hash", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voter_address", models.CharField(max_length=42)),
                ("support", models.BooleanField()),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blockchain.proposal",
                    ),
                ),
            ],
        ),
    ]
